### ISSUE TITLE
data migration for speaker.shape appears to not be calculating boundary and attenuation_border fields

### ISSUE THREAD

**Issue by hburgund** [probabble/roundware-server#5]
when I run data migrations on `speaker.shape`, the `shape` field is created, but when I look in the database, the `boundary` and `attenuation_border` fields are still NULL. If I open the record in the admin and save it there, the values are calculated, but this should happen automatically in the migration.

I can try to add some code in the migration file after the data conversion, but that might not be the best place for it. Maybe there's another spot in the code that will catch all of these sorts of errors of omission?

**Comment by probabble** [comment]
Yep. We need to re-save the Speaker after calculating the Speaker.shape to produce the derived geometries. Fix incoming...
